name: Keep Supabase Active

on:
  schedule:
    # Run every 6 days to prevent 7-day inactivity pause
    - cron: '0 12 */6 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install @supabase/supabase-js
        
    - name: Keep Supabase Active
      env:
        NEXT_PUBLIC_SUPABASE_URL: "https://fkzojsyipfhpimcwclhr.supabase.co"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrem9qc3lpcGZocGltY3djbGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjQ5NDUsImV4cCI6MjA3Mzk0MDk0NX0.mC-n1BPKA9o7bRF1qVHJeA7JYvVUH8N6lf0eKCM8OVU"
      run: |
        node scripts/keep-alive.js