name: Monitor Supabase Status

on:
  schedule:
    # Check daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  check-supabase:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Supabase Status
      env:
        NEXT_PUBLIC_SUPABASE_URL: "https://fkzojsyipfhpimcwclhr.supabase.co"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrem9qc3lpcGZocGltY3djbGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjQ5NDUsImV4cCI6MjA3Mzk0MDk0NX0.mC-n1BPKA9o7bRF1qVHJeA7JYvVUH8N6lf0eKCM8OVU"
      run: |
        # Test database connectivity
        response=$(curl -s -w "%{http_code}" -o /dev/null "$NEXT_PUBLIC_SUPABASE_URL/rest/v1/" \
          -H "apikey: $NEXT_PUBLIC_SUPABASE_ANON_KEY")
        
        if [ "$response" -eq 200 ]; then
          echo "✅ Supabase is active and healthy"
        else
          echo "❌ Supabase may be paused or having issues (HTTP: $response)"
          # You could add notification logic here (Slack, email, etc.)
        fi